Updating International Trade Section C intro
bitzesty/qae pull request #2026
Opened 2022-04-21 15:37 UTC by DaniBitZesty

Card: https://app.asana.com/0/1200504523179345/1202154074583682/f

![Screenshot 2022-04-21 at 16 36 45](https://user-images.githubusercontent.com/84323332/164497841-72676176-efbc-42d4-839e-a5614e394fb2.png)

2022-04-21 15:43 UTC, TheDancingClown requested changes

2022-04-21 15:43 UTC, TheDancingClown commented on app/forms/award_years/v2023/international_trade/international_trade_step3.rb
>              <h3 class="govuk-heading-m">COVID-19 impact</h3>
Remove the COVID header and paragraph

2022-04-21 15:47 UTC, DaniBitZesty commented on app/forms/award_years/v2023/international_trade/international_trade_step3.rb
>              <h3 class="govuk-heading-m">COVID-19 impact</h3>
Wasn't highlighted in blue but looks like it's pretty much a duplicate of the covid paragraph

2022-04-21 15:50 UTC, TheDancingClown approved these changes

2022-04-22 13:07 UTC, TheDancingClown approved these changes

2022-04-22 13:26 UTC, merged