QA copy changes VOFF
bitzesty/qae pull request #2146
Opened 2022-10-11 12:08 UTC by TheDancingClown

https://app.asana.com/0/home/1200061634431011/1203115775652532

Copy changes - see asana sub-tasks for details.

2022-10-11 13:26 UTC, dreamfall requested changes

2022-10-11 13:26 UTC, dreamfall commented on app/renderers/mail_renderer.rb
> -      d.strftime(format)
we should assign it to a var to avoid calling `strftime` 3 times most of the time.

2022-10-11 13:26 UTC, dreamfall commented on app/views/admin/form_answers/_financials_review.html.slim
> +            = render "admin/form_answers/financial_summary/shortlisted_financial_docs", docs_wrapper: resource.shortlisted_documents_wrapper
this is not correct, we should display it unless `resource.requires_vocf?`. But we already check it at the top change is not needed.

2022-10-11 13:26 UTC, dreamfall commented on spec/features/assessor/review_shortlisted_docs_spec.rb
> +# This test suite has been marked as pending as the functionality for assessors to download audit certificates has been temporarily removed to see how the current system functions
This should still work

2022-10-11 14:06 UTC, TheDancingClown commented on app/views/admin/form_answers/_financials_review.html.slim
> +            = render "admin/form_answers/financial_summary/shortlisted_financial_docs", docs_wrapper: resource.shortlisted_documents_wrapper
I have changed the policy for downloading the commercial figures. This policy is only used in one place and we have been asked to remove the download link for assessors and admins

2022-10-11 14:06 UTC, TheDancingClown commented on spec/features/assessor/review_shortlisted_docs_spec.rb
> +# This test suite has been marked as pending as the functionality for assessors to download audit certificates has been temporarily removed to see how the current system functions
Fixed the selector

2022-10-12 10:11 UTC, dreamfall approved these changes

2022-10-12 10:13 UTC, merged