Copy changes for winners head of organisation mailer
bitzesty/qae pull request #2277
Opened 2023-03-16 16:22 UTC by TheDancingClown

## 📝 A short description of the changes

* Copy changes for winners head of organisation mailer

### 🖼️ Screenshots (if appropriate - no PII/Prod data):

<img width="739" alt="Screenshot 2023-03-16 at 16 21 07" src="https://user-images.githubusercontent.com/65811538/225685791-936ee946-c4f5-4f7e-b7ce-fe728534f997.png">
<img width="740" alt="Screenshot 2023-03-16 at 16 21 22" src="https://user-images.githubusercontent.com/65811538/225685804-db2260b5-70e4-4560-99af-6ab51a790c00.png">

## 🔗 Link to the relevant story (or stories)

* https://app.asana.com/0/1200504523179345/1204178537252527

## :shipit: Deployment implications

* None

## ✅ Checklist

- [x] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [x] I have checked that commit messages make sense and explain the reasoning for each change
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have squashed any unnecessary or part-finished commits
- [x] I have attached screenshots of visual changes

2023-03-16 16:48 UTC, Lubosky submitted a review, later dismissed

2023-03-16 18:15 UTC, TheDancingClown commented on app/mailers/application_mailer.rb
> +  end
Refactored to set_deadline methods which are called before_action in each mailer class where needed.

2023-03-17 10:35 UTC, dreamfall requested changes

2023-03-17 10:35 UTC, dreamfall commented on app/views/users/winners_head_of_organisation_mailer/preview/notify.html.slim
> +    =< "#{@book_notes_deadline_with_time_and_day}"
```suggestion
    =< @book_notes_deadline_with_time_and_day
```

2023-03-17 11:18 UTC, dreamfall approved these changes

2023-03-17 11:19 UTC, merged