Financial summary table: fix save action
bitzesty/qae pull request #2493
Opened 2023-08-14 13:48 UTC by saenom

## 📝 A short description of the changes

* The financial summary section of the form answer in admin view saves on each keystroke, which renders the cancel and save button redundant. This pull request changes the financial summary section to only save when clicking on the save button.

## 🔗 Link to the relevant story (or stories)

asana: https://app.asana.com/0/1200504523179345/1204412218516929/f

## :shipit: Deployment implications

* 

## ✅ Checklist

- [ ] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [ ] I have checked that commit messages make sense and explain the reasoning for each change
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have squashed any unnecessary or part-finished commits

## 🖼️ Screenshots (if appropriate - no PII/Prod data):

2023-08-14 18:25 UTC, TheDancingClown requested changes

2023-08-14 18:25 UTC, TheDancingClown commented on app/assets/javascripts/admin/financial_data.js.coffee
> +#      timer ||= setTimeout(saveFinancials, 500)
We can remove this if not being used.

2023-08-15 09:44 UTC, saenom commented on app/assets/javascripts/admin/financial_data.js.coffee
> +#      timer ||= setTimeout(saveFinancials, 500)
I removed this code

2023-08-15 12:29 UTC, TheDancingClown approved these changes

2023-08-15 13:31 UTC, merged