Adds timeout warning popup
bitzesty/qae pull request #2525
Opened 2023-08-24 11:47 UTC by TheDancingClown

## 📝 A short description of the changes

* Shows a warning popup with 5 minutes remaining to admins/assessors/judges and gives the option to extend the session

## 🔗 Link to the relevant story (or stories)

* https://app.asana.com/0/1204861597377754/1205067405053454

## :shipit: Deployment implications

* None

## ✅ Checklist

- [x] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [x] I have checked that commit messages make sense and explain the reasoning for each change
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have squashed any unnecessary or part-finished commits

## 🖼️ Screenshots (if appropriate - no PII/Prod data):

<img width="1792" alt="Screenshot 2023-08-24 at 12 45 53" src="https://github.com/bitzesty/qae/assets/65811538/07e2d864-20ae-43db-8148-d9faf1f1cc5b">

2023-08-25 13:21 UTC, Lubosky requested changes

2023-08-25 13:21 UTC, Lubosky commented on app/models/user.rb
> +    1200.minutes
This would be better to put in ENV variable in case we want to quickly change it - can have 20 hrs as default value. Also better to use hours for readability.

2023-08-25 13:21 UTC, Lubosky commented on app/views/shared/_timeout_warning_popup.html.slim
> +          = "minutes you will be automatically logged out because of prolonged inactivity (#{distance_of_time_in_words(Time.now, Time.now + current_subject.timeout_in, only: [:minutes, :hours])}), to
Maybe move to locale file so you get plural right... 1 minute, 2 minutes

2023-08-29 08:49 UTC, TheDancingClown commented on app/views/shared/_timeout_warning_popup.html.slim
> +          = "minutes you will be automatically logged out because of prolonged inactivity (#{distance_of_time_in_words(Time.now, Time.now + current_subject.timeout_in, only: [:minutes, :hours])}), to
I've done this in the javascript instead as this is where the time is added

2023-08-29 13:39 UTC, merged