External accountants report changes
bitzesty/qae pull request #2648
Opened 2023-10-20 15:35 UTC by DaniBitZesty

## 📝 A short description of the changes

* 

## 🔗 Link to the relevant story (or stories)

* https://app.asana.com/0/1200504523179343/1205737775276248/f

## :shipit: Deployment implications

* 

## ✅ Checklist

- [ ] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [ ] I have checked that commit messages make sense and explain the reasoning for each change
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have squashed any unnecessary or part-finished commits

## 🖼️ Screenshots (if appropriate - no PII/Prod data):

2023-10-20 16:34 UTC, Lubosky requested changes

2023-10-20 16:34 UTC, Lubosky commented on app/pdf_generators/pdf_audit_certificates/general/guidance_elements.rb
> +    p1 = "The financial figures should be in pound sterling (£). Please note that all figures should be in full. NOT rounded to the nearest thousand etc.. Rounded figures will be rejected."
etc.. should be etc.

2023-10-23 09:37 UTC, Weddin approved these changes

2023-10-23 09:37 UTC, Weddin commented on app/pdf_generators/pdf_audit_certificates/awards2016/promotion/base.rb
> +      "Enterprise Promotion"
What do you think about extended `PdfAuditCertificates::Base` as
```ruby
def award_type_short
  I18n.t("pdf.audit_certificates")[self.class_name.underscore]['awart_type_short']
end
```
For raising errors or 
```ruby
I18n.t("pdf.audit_certificates").dig(class_name.underscore,'awart_type_short') || class_name.titleize
```
For default value?

2023-10-23 10:57 UTC, DaniBitZesty commented on app/pdf_generators/pdf_audit_certificates/awards2016/promotion/base.rb
> +      "Enterprise Promotion"
@alexey-klimuk I've pushed a change but it looks a bit messy, this is the only way I could extract the award name through the base module. Let me know what you think

2023-10-23 15:30 UTC, merged