Copy updates to Palace invite form
bitzesty/qae pull request #2850
Opened 2024-05-01 15:17 UTC by TheDancingClown

## 📝 A short description of the changes

* Copy updates to palace invite form

## 🔗 Link to the relevant story (or stories)

* https://app.asana.com/0/1200504523179343/1207204405967425

## :shipit: Deployment implications

* None

## ✅ Checklist

- [x] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [x] I have checked that commit messages make sense and explain the reasoning for each change
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have squashed any unnecessary or part-finished commits

## 🖼️ Screenshots (if appropriate - no PII/Prod data):

<img width="264" alt="Screenshot 2024-05-01 at 16 13 08" src="https://github.com/bitzesty/qae/assets/65811538/2b1787cb-d413-43ac-bcf1-d6fcef607f00">

2024-05-01 15:36 UTC, matthewford approved these changes

2024-05-02 08:25 UTC, dreamfall requested changes

2024-05-02 08:25 UTC, dreamfall commented on app/decorators/trigger_at_decorator.rb
> +      trigger_on = object.trigger_at.strftime("%-d %B %Y,")
I don't think comma is intentional. 

```suggestion
      trigger_on = object.trigger_at.strftime("%-d %B %Y")
```

2024-05-02 08:25 UTC, dreamfall commented on app/views/admin/form_answers/winners_components/_palace_attendee.html.slim
> +          p= pa.disabled_access? && pa.disabled_access.presence || "-"
one check should be enough
```suggestion
          p= pa.disabled_access.presence || "-"
```

2024-05-02 08:26 UTC, TheDancingClown commented on app/decorators/trigger_at_decorator.rb
> +      trigger_on = object.trigger_at.strftime("%-d %B %Y,")
Also changing the month format from Jul to July

2024-05-02 09:54 UTC, TheDancingClown commented on app/decorators/trigger_at_decorator.rb
> +      trigger_on = object.trigger_at.strftime("%-d %B %Y,")
Refactored trigger_at_decorator

2024-05-02 09:57 UTC, dreamfall approved these changes

2024-05-02 10:11 UTC, merged