Fixing RuboCop issues
bitzesty/qae pull request #2919
Opened 2024-05-10 02:23 UTC by Lubosky

## 📝 A short description of the changes

Continuation of work started in #2901 & fixing more RuboCop issues.

 - added `.editorconfig` file to apply some basic formatting 

## 🔗 Link to the relevant story (or stories)

Asana card here: https://app.asana.com/0/1200504523179343/1207221131279502

## :shipit: Deployment implications

None.

## ✅ Checklist

- [ ] Features that cannot go live are behind a feature flag/env var or specify deploy date and open PR as draft 
- [ ] I have checked that commit messages make sense and explain the reasoning for each change
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have squashed any unnecessary or part-finished commits

## 🖼️ Screenshots (if appropriate - no PII/Prod data):

2024-05-15 08:27 UTC, dreamfall requested changes

2024-05-15 15:04 UTC, Lubosky commented on app/services/current_award_type_picker.rb
> +      true if visible_categories.size > 1
Yep, it's better like that. Thank you.

2024-05-15 15:04 UTC, Lubosky commented on sic_codes.yml
Removed. Was just testing something I did not understand. Thought I didn't commit this though.

2024-05-20 14:42 UTC, dreamfall approved these changes

2024-06-11 14:28 UTC, merged